CREATE TABLE workwork_jobcontacts (
    id INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    contactname TEXT NOT NULL,
    contacttitle TEXT NOT NULL,
    contactnumber TEXT NOT NULL,
    date_added TIMESTAMPTZ NOT NULL DEFAULT now(),
    card_id INTEGER REFERENCES workwork_jobcards(id) ON DELETE CASCADE NOT NULL
);