CREATE TABLE workwork_studycards (
    id INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    trainingname TEXT NOT NULL,
    trainingurl TEXT NOT NULL,
    card_added TIMESTAMPTZ DEFAULT now() NOT NULL,
    comments TEXT,
    user_id INTEGER REFERENCES workwork_users(id) ON DELETE CASCADE NOT NULL
);