CREATE TABLE workwork_studyevents (
    id INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    event_type TEXT NOT NULL,
    date_added TIMESTAMPTZ NOT NULL DEFAULT now(),
    card_id INTEGER REFERENCES workwork_studycards(id) ON DELETE CASCADE NOT NULL
);